### ISSUE TITLE
blue fonts

### ISSUE THREAD

**Issue by arczi84** [EXL/NXEngine#1]
Hi, I made Polish translation base on your code but all polish fonts are blue.
I see that rusian are also blue. Any idea how to make them white?
I noticed this happens for fonts above 0x7F.

**Comment by EXL** [comment]
Can you send some screens with blue fonts?

Thanks for reporting.

**Comment by arczi84** [comment]
Interesting thing, is that with gcc 6.3 and O2 flag colors are good , but
it crash on F3 key( but this could be due to it's WIP).
​

2017-09-09 2:11 GMT+02:00 EXL <notifications@github.com>:

**Comment by EXL** [comment]
I noticed that on GCC 7.2.0 the project is not build at all

I slightly fixed the code: 7ce8b065

Please try, maybe now the problem is gone.

![screenshot_20170910_031806](https://user-images.githubusercontent.com/232116/30243611-bd150108-95d7-11e7-935e-87ba0997e830.png)

**Comment by arczi84** [comment]
Still blue on gcc 3.4. Only on gcc 6.3 with O2 flag I get white letters but
it crash if I go to Options with F3.
Do you have gcc 3.4 to try?
How about ingame font color?

2017-09-09 22:25 GMT+02:00 EXL <notifications@github.com>:

**Comment by EXL** [comment]
@arczi84 I tested now on GCC 3.4.6 (i386 arch, Debian etch) and also on GCC 3.4.3 (armv6 arch, MotoMAGX linux) and GCC 3.3.6 (armv5 arch, MotoEZX linux) long time ago... 

I didn't have any problems with blue fonts or crashes, all OK in menus and ingame dialogues

Which CPU arch, OS and environment you use? Maybe GCC flag `-funsigned-char` can help you?

Hmm... can there be some problems with SDL_ttf or Freetype?

![screenshot_20170910_083350](https://user-images.githubusercontent.com/232116/30245576-7d4a1726-9608-11e7-9887-ac6cff4db696.png)

![screenshot_20170910_083757](https://user-images.githubusercontent.com/232116/30245578-88ad2e6e-9608-11e7-8807-9aadcc93afb7.png)

**Comment by EXL** [comment]
Ok then.

**Comment by arczi84** [comment]
Hello, problem is solved now with help of a much better coder than me :)

`char utf8_str[2];`

changed to

`char utf8_str[2*4];`

That's it!

**Comment by EXL** [comment]
@arczi84 Thanks for the published solution.
