### ISSUE TITLE
Cannot shoot up while running to the right

### ISSUE THREAD

**Issue by atirutw** [EXL/NXEngine#15]
I don't have the time to confirm if this is an isolated case at the moment, but I encountered this on Windows 7 Ultimate 32 bit.

**Comment by EXL** [comment]
@atirut-w
Can't confirm, sorry.

https://user-images.githubusercontent.com/232116/216280645-c5d68602-cedb-4a32-b82b-f90e622c6851.mp4

**Comment by atirutw** [comment]
You press shoot while aiming up *and* walking to the right.

**Comment by atirutw** [comment]
Tried this on Linux and the bug does not happen. I guess it's a problem with either Windows 7 or the specific machine I'm running it on, which is an ancient workplace computer.

**Comment by EXL** [comment]
> You press shoot while aiming up _and_ walking to the right.


https://user-images.githubusercontent.com/232116/216341222-774872a0-651f-4954-945e-f6dfa7347397.mp4

Like this?

>Tried this on Linux and the bug does not happen. I guess it's a problem with either Windows 7 or the specific machine I'm running it on, which is an ancient workplace computer.

Is Linux on the same machine? If no, maybe it's just the limitations of the keyboard controller which does not allow multiple buttons to be pressed.

**Comment by atirutw** [comment]
Either the keyboard controller or the ancient Windows install then.
